# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getScanNumber <- function(ds) {
    .Call('Rdrp_getScanNumber', PACKAGE = 'Rdrp', ds)
}

getZeros <- function(n) {
    .Call('Rdrp_getZeros', PACKAGE = 'Rdrp', n)
}

